name    'erwbgy-lumberjack'
version '0.1.0'
source 'https://github.com/erwbgy/puppet-lumberjack.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Run Tomcat instances under Runit'
description 'Run Tomcat instances under Runit'
project_page 'http://forge.puppetlabs.com/erwbgy/lumberjack'
dependency 'erwbgy/runit', '>= 0.4.1'
